using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WorkWell.ViewModels
{
    public class PayslipDocument : IDocument
    {
        private readonly string employeeName;
        private readonly int employeeId;
        private readonly int month;
        private readonly int year;
        private readonly decimal basicSalary;
        private readonly decimal allowances;
        private readonly decimal totalSalary;

        public PayslipDocument(string name, int id, int month, int year, decimal basic, decimal allow, decimal total)
        {
            employeeName = name;
            employeeId = id;
            this.month = month;
            this.year = year;
            basicSalary = basic;
            allowances = allow;
            totalSalary = total;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(40);

                page.Header().Text($"Payslip - {employeeName}").FontSize(20).Bold().AlignCenter();

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Text($"Name: {employeeName}").FontSize(14);
                    col.Item().Text($"Employee ID: {employeeId}").FontSize(14);
                    col.Item().Text($"Month: {month}").FontSize(14);
                    col.Item().Text($"Year: {year}").FontSize(14);
                    col.Item().Text($"Basic Salary: {basicSalary:C}").FontSize(14);
                    col.Item().Text($"Allowances: {allowances:C}").FontSize(14);
                    col.Item().Text($"Total Salary: {totalSalary:C}").FontSize(14).Bold();
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by WorkWell HR System ").FontSize(10);
                });
            });
        }

        public void GeneratePdf(string filePath)
        {
            Document.Create(container => Compose(container)).GeneratePdf(filePath);
        }
    }
}
